version: '3'
services:
  redis:
    image: "redis:5-alpine"
    ports:
      - "6379:6379"
  postgres:
    image: "postgres:10-alpine"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: morphocut
      POSTGRES_PASSWORD: morphocut
      POSTGRES_DB: morphocut