"""empty message

Revision ID: 0d7418bf1cea
Revises: 
Create Date: 2018-12-18 05:57:36.379504

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0d7418bf1cea'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('datasets', sa.Column('name', sa.String(), nullable=True))
    op.add_column('datasets', sa.Column('objects', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('datasets', 'objects')
    op.drop_column('datasets', 'name')
    # ### end Alembic commands ###
