"""empty message

Revision ID: 730ceb99dce1
Revises: bf7aa5f85087
Create Date: 2019-01-07 22:21:05.917988

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '730ceb99dce1'
down_revision = 'bf7aa5f85087'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('datasets', sa.Column('path', sa.String(), nullable=True))
    op.add_column('objects', sa.Column('modification_date', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('objects', 'modification_date')
    op.drop_column('datasets', 'path')
    # ### end Alembic commands ###
