"""empty message

Revision ID: 82a2af59ea3a
Revises: a64169f38d7c
Create Date: 2019-02-25 14:54:41.168386

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '82a2af59ea3a'
down_revision = 'a64169f38d7c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('projects',
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('author', sa.String(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('creation_date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('project_id')
    )
    op.create_table('contributors',
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.project_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], )
    )
    op.create_index(op.f('ix_contributors_project_id'), 'contributors', ['project_id'], unique=False)
    op.create_index(op.f('ix_contributors_user_id'), 'contributors', ['user_id'], unique=False)
    op.create_table('facets',
    sa.Column('object_id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(), nullable=True),
    sa.Column('creation_date', sa.DateTime(), nullable=True),
    sa.Column('modification_date', sa.DateTime(), nullable=True),
    sa.Column('dataset_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['dataset_id'], ['datasets.dataset_id'], ),
    sa.PrimaryKeyConstraint('object_id')
    )
    op.create_index(op.f('ix_facets_dataset_id'), 'facets', ['dataset_id'], unique=False)
    op.add_column('objects', sa.Column('project_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_objects_project_id'), 'objects', ['project_id'], unique=False)
    op.drop_index('ix_objects_dataset_id', table_name='objects')
    op.drop_constraint(None, 'objects', type_='foreignkey')
    op.create_foreign_key(None, 'objects', 'projects', ['project_id'], ['project_id'])
    op.drop_column('objects', 'dataset_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('objects', sa.Column('dataset_id', sa.INTEGER(), nullable=True))
    op.drop_constraint(None, 'objects', type_='foreignkey')
    op.create_foreign_key(None, 'objects', 'datasets', ['dataset_id'], ['dataset_id'])
    op.create_index('ix_objects_dataset_id', 'objects', ['dataset_id'], unique=False)
    op.drop_index(op.f('ix_objects_project_id'), table_name='objects')
    op.drop_column('objects', 'project_id')
    op.drop_index(op.f('ix_facets_dataset_id'), table_name='facets')
    op.drop_table('facets')
    op.drop_index(op.f('ix_contributors_user_id'), table_name='contributors')
    op.drop_index(op.f('ix_contributors_project_id'), table_name='contributors')
    op.drop_table('contributors')
    op.drop_table('projects')
    # ### end Alembic commands ###
