"""User login via email instead of username

Revision ID: 860c6ff76ea8
Revises: 94c25916378f
Create Date: 2019-06-06 11:06:01.812026

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '860c6ff76ea8'
down_revision = '94c25916378f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('email', sa.String(length=255)))
    op.drop_constraint('users_username_key', 'users', type_='unique')
    op.create_unique_constraint('users_email_key', 'users', ['email'])
    op.drop_column('users', 'username')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column(
        'username', sa.VARCHAR(), autoincrement=False))
    op.drop_constraint('users_email_key', 'users', type_='unique')
    op.create_unique_constraint('users_username_key', 'users', ['username'])
    op.drop_column('users', 'email')
    # ### end Alembic commands ###
