"""Add meta field to Task table

Revision ID: a4a031f74720
Revises: 860c6ff76ea8
Create Date: 2019-06-08 14:12:10.983247

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'a4a031f74720'
down_revision = '860c6ff76ea8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('meta', postgresql.JSON(
        astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('task', 'meta')
    # ### end Alembic commands ###
