"""Initial model

Revision ID: c7d377355876
Revises: 
Create Date: 2019-01-08 09:29:24.210991

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c7d377355876'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('datasets',
                    sa.Column('dataset_id', sa.Integer(), nullable=False),
                    sa.Column('name', sa.String(), nullable=True),
                    sa.Column('author', sa.String(), nullable=True),
                    sa.Column('path', sa.String(), nullable=True),
                    sa.Column('active', sa.Boolean(), nullable=True),
                    sa.Column('creation_date', sa.DateTime(), nullable=True),
                    sa.PrimaryKeyConstraint('dataset_id')
                    )
    op.create_table('users',
                    sa.Column('user_id', sa.Integer(), nullable=False),
                    sa.Column('name', sa.String(), nullable=True),
                    sa.Column('email', sa.String(), nullable=True),
                    sa.PrimaryKeyConstraint('user_id')
                    )
    op.create_table('objects',
                    sa.Column('object_id', sa.Integer(), nullable=False),
                    sa.Column('filename', sa.String(), nullable=True),
                    sa.Column('creation_date', sa.DateTime(), nullable=True),
                    sa.Column('modification_date',
                              sa.DateTime(), nullable=True),
                    sa.Column('dataset_id', sa.Integer(), nullable=True),
                    sa.ForeignKeyConstraint(
                        ['dataset_id'], ['datasets.dataset_id'], ),
                    sa.PrimaryKeyConstraint('object_id')
                    )
    op.create_index(op.f('ix_objects_dataset_id'),
                    'objects', ['dataset_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_objects_dataset_id'), table_name='objects')
    op.drop_table('objects')
    op.drop_table('users')
    op.drop_table('datasets')
    # ### end Alembic commands ###
