"""empty message

Revision ID: f2b0dafe08f3
Revises: 0d7418bf1cea
Create Date: 2019-01-03 17:23:55.229625

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f2b0dafe08f3'
down_revision = '0d7418bf1cea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('objects', sa.Column('filename', sa.String(), nullable=True))
    op.drop_column('objects', 'filepath')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('objects', sa.Column('filepath', sa.VARCHAR(), nullable=True))
    op.drop_column('objects', 'filename')
    # ### end Alembic commands ###
